export const PATH = {
  hr: "/ai-services/ai-hr-assistant",
  sales: "/ai-services/ai-sales-assistant",
  monitor: "/ai-services/ai-model-monitoring",
  workflow: "/ai-services/ai-workflow-automation",
  deploy: "/ai-services/ai-model-deployment",
  chatbots: "/ai-services/enterprise-chatbots",
  docIntel: "/ai-services/document-intelligence",
  support: "/ai-services/customer-support-agents",
  knowledge: "/ai-services/enterprise-knowledge-base-agents",
  infra: "/ai-services/ai-infrastructure",
  dev: "/ai-services/ai-development-services",
  mvp: "/ai-services/ai-mvp-development",
  chatgpt: "/ai-services/chatgpt-enterprise-integration",
  readiness: "/ai-services/ai-readiness-assessment",
  roadmap: "/ai-services/ai-strategy-roadmap",
  saas: "/ai-services/ai-saas-product-development",
  multiAgent: "/ai-services/multi-agent-systems",
} as const;
